mutation CreateBooking(
  $passengerId: ID!,
  $flightId: ID!,
  $bookingDate: String!,
  $status: String!
) {
  createBooking(
    passengerId: $passengerId
    flightId: $flightId
    bookingDate: $bookingDate
    status: $status
  ) {
    id
    passenger {
      id
      firstName
      lastName
      passportNumber
      phoneNumber
      email
    }
    flight {
      id
      name
      originAirport {
        id
        name
        city
        country
        code
      }
      destinationAirport {
        id
        name
        city
        country
        code
      }
      departureTime
      arrivalTime
      airline {
        id
        name
        code
        country
      }
    }
    bookingDate
    status
  }
}
