mutation createFlight(
    $name: String!
    $departureTime: String!
    $arrivalTime: String!
    $airline: ID!
    $routeId: ID!
) {
    createFlight(
        name: $name
        arrivalTime: $arrivalTime
        departureTime: $departureTime
        airline: $airline
        routeId: $routeId
    ) {
        id
        name
        departureTime
        arrivalTime
        route {
            id
            routeCode
            description
            origin {
                id
                name
                code
                city
                country
            }
            destination {
                id
                name
                code
                city
                country
            }
            flights {
                id
                name
            }
        }
        airline {
            id
            name
            code
            country
        }
    }
}