query flightDetails(
    $name: String!
) {
    getFlightByName(
        name: $name
    ) {
        name
        departureTime
        arrivalTime
        airline {
            id
            name
            code
            country
        }
        route {
            id
            routeCode
            origin {
                id
                name
                code
                country
            }
            destination {
                id
                name
                code
                country
            }
        }
    }
}