query (
    $name: String!
    $price: Float
    $status: String
    $airline: String
) {
    getFlightByName(
        name: $name
        price: $price
        status: $status
        airline: $airline
    ) {
        name
        seats
        color
        airline
        price
        status
    }
}